LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIMission_LWCustomMission.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIMission_LWLaunchDelayedMission.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIUtilities_LW.uc

Fixes #16 and #17
The interaction between the base `UIMission` and mission-specific
subtypes changed in WotC and the LW version needed some updates. This
change goes through the `UIMission_GOps` class from WOTC and updates the
LW version to be roughly equivalent.
In particular the class needs an empty `OnButtonSizeRealized` function
to avoid the base version moving the confirm button around (#16), and
the screen building needs to invoke the base class `BuildScreen` to
properly set up the chosen and sitrep UI elements (among others) so
they will be hidden when appropriate (#17).
It's probably better to split this file up into separate versions for
different mission types, but I didn't do that here. Non-GOp missions
may still have bugs because of this. Dark Event display may need
updating …

Fix several issues with the GOp mission UI

---

LongWarOfTheChosen/Src/LW_Toolbox_Integrated/Classes/XComGameState_LWToolboxOptions.uc

`GetHPChangedObjectList` was pulling the previous game state with an
uninitialized variable, so would always yield `none` and ignore all
HP-changing events.

Fix Red Fog

---

LongWarOfTheChosen/Config/XComEngine.ini
LongWarOfTheChosen/LongWarOfTheChosen.x2proj
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIStrategyMapItem_AlienNetworkComponent_LW.uc

This push is to fix the issue of not being able to infiltrate alien
facilities (Issue #139). You can now infiltrate a facility and complete
it successfully. It will remove the amount of doom the facility has but
will not play the animation and display the notification of having done
so. This isa WIP commit and will need to figure out the hook to call to
play the animation.

Unable to infiltrate alien facility fix (#139)

---

LongWarOfTheChosen/Src/LW_AlienPack_Integrated/Classes/X2Item_LWAlienWeapons.uc

Naja should not be able to move and shoot so adjusted the cost to shoot
their rifle to cost 2 AP.

Adjust Naja Rifle AP Cost (#162)

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIMission_LWCustomMission.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIMission_LWLaunchDelayedMission.uc

The Shadow Chamber had 2 issues. The first was that it displayed
information for missions that were not Golden Path missions or Alien
Facility missions which it was not supposed to do. The second issue
was that it set alert level to all missions to 1 which caused baseline
enemy activity to be wrong (too low) for a lot of the regions come late
game.

Shadow Chamber Issues Fix (#140)

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTacticalMissionUnitSpawner.uc

This fix is for fixing the issue of haven advisers not getting any
abilities at all (not from perks, weapons, items, etc..). Looks like
Firaxis added a BeginTacticalPlay() function to some of the XCGS
classes that has to be called to properly load in the abilities.
This fifx just added the function calls in the proper places.

Haven Adviser Fix (#159)

---

LongWarOfTheChosen/Config/XComLW_Overhaul.ini

Make the reusable weapon upgrades tech unresearchable as it is a base feature in LW. Fixes #179.

Disable reusable weapon upgrades breakthrough

---

LongWarOfTheChosen/Config/XComPromotionUIMod.ini

There was a bug with the New Promotion Screen By Default mod that made
it so that when you chose to put someone in officer training the game
would go to the soldier's ability page instead of the officer ability
page.
The credit for this fix goes to Martox.

Fix officer slot in gts with NPSBD mod on

---

LongWarOfTheChosen/Config/XComGameData.ini

With NPSBD being integrated it caused abilities at the MSGT rank to
cost 0 AP so a quick ini addition was made to fix.

Added ini tweak to fix MSGT abilities cost (#254)

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_TechnicalAbilitySet.uc

The ability burnout was not updating the tile that the soldier was
standing in to give it the smoke cover bonus but was updating the tiles
adjacent to the unit. For some reeason the ability tempaltes multi
target effect for smoke only updated the adjacent tiles. This was fixed
by adding a single target effect that applied to the tile that the
soldier was on.

Fix for burnout ability #233

---

LongWarOfTheChosen/Config/XComLW_Activities.ini

Not sure what LW2 was doing here since it is also missing this bit of config and gives a Council Message alert with only one button. But this will fix the immediate issue in #251.

Council Mission alert screen for HQ Assault

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc

Chosen Hunter pistol was not classified as a utility slot pistol. Added
the needed code in LWTemplateMods to change it. It does the same thing
that is done for the alien hunter pistol.

Make Darkclaw a Utility Item (#341)

---

LongWarOfTheChosen/Config/XComClassData.ini
LongWarOfTheChosen/Config/XComGameData.ini
LongWarOfTheChosen/Config/XComLW_InfiltrationSettings.ini
LongWarOfTheChosen/Config/XComLW_OfficerPack.ini
LongWarOfTheChosen/Src/LW_AlienPack_Integrated/Classes/X2Item_LWAlienWeapons.uc
LongWarOfTheChosen/Src/LW_LaserPack_Integrated/Classes/X2Item_LaserWeapons.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Item_Coilguns.uc
LongWarOfTheChosen/Src/LW_SMGPack_Integrated/Classes/X2Item_SMGWeapon.uc

SMGs were getting the damage bonus from the assault rifle weapon
breakthrough. This was because their weapon category was 'rifle' which
is the same category as the assualt rifle. Changed the weapon category
to 'smg' and added the needed lines in XComClassData.ini to allow the
classes that could equipem them to continue to equip them.

Changed SMG Weapon Category (#317)

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIPersonnel_Liaison.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_Soldiers.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/XComGameState_LWOutpost.uc

- Can no longer select shaken soldiers to be advisers
- If an adviser becomes shaken on/after a mission, they will be removed as an adviser
- Shaken and Rank Too Low soldier statuses now have higher priority than Unit in Squad when on the select adviser screen

#461 Shaken soldiers can no longer serve as haven advisers

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_GunnerAbilitySet.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Ability_PerkPackAbilitySet.uc

Slash and Knife Fighter can now target enemies whom you have mind-controlled. Closes #578

#578 Slash and Knife Fighter can now target mind-controlled units

---

LongWarOfTheChosen/Config/XComGame.ini
LongWarOfTheChosen/Localization/BetterSecondWaveSupport.int
LongWarOfTheChosen/Src/NewPromotionScreenByDefault_Integrated/Classes/NPSBDP_UIArmory_PromotionHero.uc

Added an Advanced Option to allow XCOM soldiers to purchase multiple perks per rank, as long as the Training Center has been built. Closes #505

#505 Added an Advanced Option to allow XCOM soldiers to purchase multiple perks per rank

---

LongWarOfTheChosen/Config/XComSchedules.ini

As per #749 , faceless spawn schedules have been removed from guerrilla ops, guerrilla vehicle, and extract schedules, leaving the dark event spawns intact.
Other lines had to be updated to keep array index values sequential.

Faceless Spawn Fix v2 #749

---

LongWarOfTheChosen/Config/XComSchedules.ini

Guerilla_Revealed_D2_2_LW previously had 10 enemies due to a lone drone at the bottom of the list. Changed OPNx3_Standard_LW to OPNx2_Standard_LW to keep difficulty in line with other str2 schedules.

Str 2 SnG schedule fix

---

LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/X2StrategyElement_LW_OTS_OfficerStaffSlot.uc

OTS staff slots were previously both costing 1 power themselves (from lines 66 and 92 that each read `Template.iPower = -1`) and increasing the GTS' base facility cost by 1. I simply commented out the line that increased the base facility's power cost.

GTS Slot Power cost from 2 to 1, Issue #802

---

LongWarOfTheChosen/Config/XComAI.ini
LongWarOfTheChosen/LongWarOfTheChosen.x2proj
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2LWAbilitiesModTemplate.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Condition_IsStunned_LW.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Condition_RevivalProtocolRestoreActionPoints_LW.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Condition_RevivalProtocol_LW.uc

Contains fixes for enemies shooting rockets/spitting poison through walls and solves the various issues with Revival Protocol granting extra action points to the target when it shouldn't.
I have made the Micro Missiles' AoE profiles require line of sight along with the other AoE abilities, but I'm not sure whether this will prevent MEC Archers from using their micro missiles at squadsight range, which is kind of the point of the unit. Would like to just include the fix, though, and see whether it has any noticeable effect on the Archers.

Miscellaneous bug fixes

---

LongWarOfTheChosen/Config/XComGameData.ini
LongWarOfTheChosen/Localization/XComGame.int
LongWarOfTheChosen/LongWarOfTheChosen.x2proj
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_SitRepGrantedAbilitySet_LW.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_FireEventOnCrit.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2SitRep_DefaultSitRepEffects_LW.uc

Replaced the Location Scout sit rep with one that grants all squad members Tracking, and also added another sit rep that grants Combat Rush On Crit, which is like Combat Rush but triggers on any crit, not on kills. This works for both ADVENT and XCOM.

New sit reps

---

LongWarOfTheChosen/Config/XComGameBoard.ini
LongWarOfTheChosen/Config/XComLW_Overhaul.ini
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_Headquarters.uc

Early covert actions should be slightly more likely to succeed, but the risk chance ramps up with force level more quickly. This is to prevent mid-game covert actions being reliably done with just LCPLs and CPLs. The effect of each rank has also been reduced for the same reason.
Lastly, I've added a cap on the FL increases so that MSGT squads can reliably complete covert actions throughout the game, rather than then having significant chances to fail by FL20.

Rebalance failure risk chances for CAs

---

LongWarOfTheChosen/Localization/LW_FactionBalance/LW_FactionBalance.int
LongWarOfTheChosen/LongWarOfTheChosen.x2proj
LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2Effect_VoidConduitPatch.uc
LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2LWModTemplate_TemplarAbilities.uc

For an explanation of the fix, see the `FixVoidConduit()` function in `X2LWModTemplate_TemplarAbilities`. It basically ensures that the targeted unit loses the appropriate number of action points at the start of its turn.

Fix Templar's Void Conduit ability

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIStrategyMapItem_Region_LW.uc

It also fixes a number of situations in which strategy map UI items (related to regions) were unselectable. Finally, spaces have been replaced with tabs.
There are a few additional issues which I have solved, but will wait until this goes through :
1.] Some region UI items do not show their 3D mesh (viewable only with a controller / not m&k - so not testable with m&k). This can either be solved by modifying or hooking XComGameState_WorldRegion --> GetStaticMesh or through a workaround whereby I override several functions within UIStrategyMapItem_Region_LW and change 1 line of code, calling my own code rather than XComGameState_WorldRegion --> GetStaticMesh.
2.] Help icons, via flash, appear when regions are selected; unfortunately, these were never designed for Long War 2 usage, so they …

Fix to Make Contact aspect of Issue # 815.

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIStrategyMapItem_Mission_LW.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIStrategyMapItem_Region_LW.uc

Modifies UIStrategyMapItem_Region_LW --> InitMapItem()
When using a controller, a (contacted) region map item can show 3 possible help icons.
1.] MapItem_Region --> consoleHint is the help icon which appears to the left of the radio tower button.
2.] StrategyScanButton --> scanHint is the help icon which appears to the right of the scan button, when visible.
3.] StrategyScanButton --> consoleHint appears to the left of the haven information button when no scan button is visible.
The problem with these help icons is that sometimes they display the wrong icon, and sometimes they overlap other UI elements. Hiding them is impossible due to the underlying flash code; consequently, the easiest way to deal with them is to remove via setting them to null.
-------------------------
Modifies …

Remove problematic, flash based, strategy map help icons when using a controller.

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIScreenListener_UIStrategyMap.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIStrategyMapItem_Region_LW.uc

Modifies UIStrategyMapItem_Region_LW --> OnUnrealCommand()
Previously, if a haven was selected with a controller, the A button would open up the haven's rebel screen; it wouldn't allow you to travel to that haven or scan there. Consequently, OnUnrealCommand() has been overridden so that :
1A.] The A button clicks the contact button of a region if it hasn't been contacted.
1B.] If 1A is false and the Avenger is in this region, the A button toggles scanning.
1C.] If 1A and 1B are false, the A button attempts to travel to the region.
2.] The X button opens up the selected haven's rebel screen.
Modifies UIScreenListener_UIStrategyMap --> OnUIStrategyMapCommand()
Previously, on the strategy map, the X button would always open up the Resistance management screen; …

Fix Region/Haven map item button clicks

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIAdventOperations_LW.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIDarkEventListItem.uc

Modifies : UIAdventOperations_LW --> GetDarkEventListUI()
The dark event list has been moved up, so as to align with the top of the dark event card to its left. Additionally, the list was made navigable so that controller users could navigate the dark event list items.
-------------------------
Modifies : UIDarkEventListItem --> OnReceiveFocus()
When a controller user navigates to a different dark event list item, we need the dark event card to update; previously this was only dealt with in mouse & keyboard code.
-------------------------
A bunch of spacing issues were dealt with as well.

Make dark event list items controller compatible

---

LongWarOfTheChosen/Src/DetailedSoldierListWOTC_Integrated/Classes/UIPersonnel_SoldierListItemDetailed.uc

Modifies : UIPersonnel_SoldierListItemDetailed
When a soldier list was loaded, the 1st D-Pad down press did nothing; strangely enough, this was not a problem with D-Pad up. It turns out that UIIcons, whose navigation is ON by default, weren't being removed from the navigation system. Consequently, navigation was removed from : APIcon, BadTraitIcon, and BonusAbilityIcon.

Detailed Soldier List Item D-Pad Down fix

---

LongWarOfTheChosen/Src/DetailedSoldierListWOTC_Integrated/Classes/UIPersonnel_SoldierListItemDetailed.uc

Modifies : UIPersonnel_SoldierListItemDetailed --> AddClassColumnIcons
Previously, the PCS stat value would not display black text when the list item was selected; consequently it was very difficult to read. The reason for this was that a call to GetStatBoostString(), which called GetColoredText(), was wrapped in a call to class'UIUtilities_Text'.static.GetColoredText(). Wrapping text in 2 font tags creates unpredictable outcomes; therefore, GetStatBoostString() was modified, to take list item selection into account, and the outer call to class'UIUtilities_Text'.static.GetColoredText() was removed.
Modifies : UIPersonnel_SoldierListItemDetailed --> GetStatBoostString
GetStatBoostString now takes a 'focused' parameter so that it can determine which colour to …

Fix Detailed Soldier Will & PCS text colour when focused.

---

LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/UIFacility_LWOfficerSlot.uc
LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/UIScreenListener_Facility.uc
LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/UIScreenListener_Facility_Academy_LWOfficerPack.uc

1.] Modifies : LW_OfficerPack_Integrated --> UIFacility_LWOfficerSlot --> OnClickStaffSlot().
When a UIStaffslot is clicked with the A button, OnUnrealCommand() simulates the click by calling OnClickStaffSlot(), and sending in FXS_L_MOUSE_UP. This case did not previously exist for the Long War slot; therefore, controllers users were unable to 'click it'. This has been fixed.
----------------------------------
2.] Added : LW_OfficerPack_Integrated --> UIScreenListener_Facility
Controller navigation, for UIFacilities, acts quite strangely at times. Here are some examples :
A.] If the rightmost staff slot is selected, and you hit D-Pad right, suddenly the room button, if one exists, becomes selected. It would be better if selection looped within the staff slot container.
B.] If you press the …

Fix finicky facility navigation for controllers + enable train officers staff slot for controllers

---

LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/UIAlert_LWOfficerTrainingComplete.uc
LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/UIArmory_LWOfficerPromotion.uc
LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/UIArmory_LWOfficerPromotionItem.uc
LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/UIScreenListener_LWOfficerPack.uc

Modifies : UIArmory_LWOfficerPromotion & UIArmory_LWOfficerPromotionItem
1.] The officer training screen has now been made controller capable; D-Pad up/down changes rows, while D-Pad left/right changes abilities. Additionally, ability selection remains consistent when changing rows; if the left ability is selected in the old row, it will also be selected in the new row; same goes for the right ability.
2.] The 'leadership history' button has been made controller capable, via a hotlink.
3.] The navigation system was also modified, for controller users, such that it would only update when necessary. The reason this was done was that each time the navigation system updates, it flickers, since it needs to clear itself, re-create itself, then show itself. 
4.] Spaces --> Tabs …

Make Officer Promotion Screen controller compatible + a few related fixes.

---

LongWarOfTheChosen/Config/XComLW_Overhaul.ini

This removes ADVENT Robotics as a requirement for Mechanized Warfare, so you don't have to acquire 3 drone wrecks, and the cost of Mechanized Warfare it much reduced. However, it does now require a MEC wreck to start the project. This adds an effective FL gate to getting your first SPARK.

Make the first SPARK easier to get

---

LongWarOfTheChosen/Config/XComLW_Overhaul.ini
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_XP.uc

Add a check to exclude a configurable list of character templates from taking a share of the end of mission exp.

Exclude defined char templates from mission exp

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIStrategyMapItem_Region_LW.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_WorldRegion.uc

Added X2EventListener_WorldRegion :
This class listens for WorldRegionGetStaticMesh and WorldRegionGetMeshScale, 2 events which are triggered within XComGameState_WorldRegion.
WorldRegionGetStaticMesh is used to make sure that, when using a controller and on the strategy map, each selectable region/haven is associated with a 3D mesh. Previously, Long War 2 introduced states which the base game did not handle; consequently, you could end up with selectable regions/havens with no 3D mesh.
WorldRegionGetMeshScale simply makes sure that the 3D mesh associated with a selectable region/haven is the correct size on the strategy map.
--------------------------------------
Modified UIStrategyMapItem_Region_LW :
UIStrategyMapItem_Region_LW.IsSelectable was previously modified to make sure that the …

Fix Region/Haven controller selectability and associated 3D mesh.

---

LongWarOfTheChosen/Config/XComAI.ini

Added LWAdventGunnerRedPostTraverseFire because LWAdventGunnerRedLastAction did not recognize action refunded by Traverse Fire and returned false.
Added TryHighPriorityShot on LWAdventGunnerRedFirstActionSelector so AI can guarantee shoot-shoot actions against vulnerable targets.
I have confirmed through testing that this allows M3 Gunner to make shoot-shoot turns against vulnerable targets. They still make move-shoot or shoot-move/overwatch etc. turns in absence of good targets.

Allow M3 Gunner to Traverse Fire (#1152)

---

LongWarOfTheChosen/Config/XComLW_Activities.ini
LongWarOfTheChosen/Src/LWUtilities/Classes/Helpers_LW.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_DefaultAlienActivities.uc
LongWarOfTheChosen/Src/LW_Toolbox_Integrated/Classes/X2StrategyElement_RandomizedSoldierRewards.uc
LongWarOfTheChosen/Src/LW_Toolbox_Integrated/Classes/XComGameState_LWToolboxOptions.uc

Jailbreaks can now have multiple captured soldiers as rewards on a single mission, making it far less troublesome to recover soldiers when the Chosen have been kidnapping a whole bunch of them.
A lot of this code is designed to ensure that each captured soldier can only be the reward for a single mission or covert action. Neither vanilla not LW2 handled this properly.

Allow rescuing multiple captured soldiers

---

LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/UIScreenListener_LWOfficerPack.uc

This fix was originally implemented for a detailed soldier list item (see pull request #1042); however, the detailed soldier list has since been replaced with a modified LW2 list. Hence, this fix was needed.
----------------------
Modifies : UIScreenListener_LWOfficerPack.AddOfficerIcon_PersonnelListItem
1.] UIPersonnel_SoldierListItem_LW.AddAdditionalItems triggers the event 'OnSoldierListItemUpdate_End' which ends up calling AddOfficerIcon_PersonnelListItem; its goal is to add an officer icon to a soldier list item, if need be. Unforunately, while icons are added to the navigation system by default, they can create controller navigation issues. In this case, the first D-Pad down press, when viewing a soldier list, would appear to be ignored. As a result, the officer icon needed to be …

Soldier List Item D-Pad Down fix

---

LongWarOfTheChosen/Config/XComAI.ini
LongWarOfTheChosen/Src/LW_AlienPack_Integrated/Classes/X2Character_AlienPack.uc

* Original AnyEnemyWithin12Tiles actually did not trigger even when there was nearby enemy, so changed it to more reliable scoring system.
* SniperMove profile modification: seeks minimum 14 tile distance with enemy visibility, low fCoverWeight so AI is willing to move to half-cover if it's only cover available far away.
* SniperMove behaviour modification: uses RestrictedDestination to guarantee cover, allows dash movement for better sniper spot search and disengagement.
* ActionSelector Behaviours reworked to call SniperMove for every movement except HuntEnemyWithCover.
* Removed RandMoveIfEnemyClose so Naja does not randomly lose opportunity to make normal sniper shots; the behaviour did not work in original anyways as MoveIfAnyEnemyWithin12Tiles had not been functional. This also made …

Naja movement AI update

---

LongWarOfTheChosen/Config/XComLW_UI.ini
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIPersonnel_SoldierListItem_LW.uc

Modifies : UIPersonnel_SoldierListItem_LW.UpdateItemsForFocus
Formerly, a soldier list item's will value and combat intelligence icon would always be coloured, even if it was disabled. This did not fit with other attribute images and values (aim/defense ... etc.) which 'grey out' when disabled. Consequently, this has been fixed.
----------------------
Added : UIPersonnel_SoldierListItem_LW.GetWillValueColor and UIPersonnel_SoldierListItem_LW.GetCombatIntelligenceColor
The function GetWillValueColor determines the will value colour based upon a soldier list item's disabled and focused status.
The function GetCombatIntelligenceColor determines the combat intelligence image's colour based upon a soldier list item's disabled and focused status.
----------------------
Modifies : XComLW_UI.ini …

Fix Soldier will value & combat intelligence colour when disabled.

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_Headquarters.uc

Modifies : X2EventListener_Headquarters
Adds a listener function, OnUIPersonnelDataRefreshed, which listens for the event 'UIPersonnel_OnSortFinished', triggered within UIPersonnel.RefreshData.
The UIPersonnel screen scrolling problem can be seen most clearly via the "View Soldiers" screen while using a controller. If you enter the "View Soldiers" screen, click on a soldier to view their information, then exit back to the "View Soldiers" screen, you may notice that the soldier list item selection remains consistent. In other words, if you click on the list item corresponding to "Doug Smith", "Doug Smith" will still be selected when you return to the "View Soldiers" screen, after viewing his information/customization options/weapon etc.
The problem is that while list item selection remains …

Personnel Screen Scrolling Fix :

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIPersonnel_SoldierListItem_LW.uc

This issue is best seen while using a controller; in order to see it do the following :
1.] Go to "View Soldiers".
2.] Click on an active soldier, someone who is infiltrating or is a haven advisor, to view their information.
3.] Exit out of the soldiers information screen back to the "View Soldiers" screen.
4.] The soldiers list item is still selected; however, ability (aim/defense/will ... etc.) text colours are not working properly.
For the following discussion it is important to note that the "View Soldiers" screen is of type UIPersonnel_Armory, which inherits from UIPersonnel.
Now, when UIPersonnel_Armory recieves focus it calls RefreshData() and eventually UpdateList().
1.] UpdateList, within the base class UIPersonnel, places focus on the soldier who …

Active Soldier list item colour fix

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIAdventOperations_LW.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_Headquarters.uc

Problem 1 : The Dark Event background does not appear.
Modifies : UIAdventOperations_LW.BuildScreen
The Long War 2 Dark Events screen, UIAdventOperations_LW, is derived from the class UIAdventOperations; this class makes use of the graphics/flash package : gfxDarkEvents.upk. When looking at the flash code, it becomes apparent that 2 graphical elements, bottomShadow and hexBackground, are only made visible through the function AnimateIn(). Unfortunately, Long War had originally commented out this code, which was called within the UnrealScript function BuildScreen. Additionally, I subsequently removed this commented out code. Therefore, these flash elements were no longer being shown.
Adding the call to AnimateIn(), via MC.FunctionVoid("AnimateIn"), fixes this issue. …

Fix Dark Event Background and Resource Bar

---

LongWarOfTheChosen/Config/XComLW_Overhaul.ini
LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc

This is so users can add GTS upgrades from other class mods to be disabled and hidden for the sake of consistency.

Config option to disable other mods' GTS upgrades

---

LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/UIScreenListener_TacticalHUD_LWOfficerPack.uc
LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/UITacticalHUD_MouseControls_LWOfficerPack.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/UITacticalHUD_AbilityContainer_LWExtended.uc

Modifies :  UITacticalHUD_AbilityContainer_LWExtended
1.] Adds : ChangeAbilityPage
Formerly, both OnScrollButtonClicked and OnUnrealCommand contained code capable of changing the ability page; consequently, there was a great deal of code duplication. This code has been consolidated into the new function ChangeAbilityPage; this function allows the ability page to be moved backwards or forwards, depending upon the parameter PreviousPage.
2.] Modifies : UpdateAbilitiesArray
Added a bit of code, previously only found in UITacticalHUD_AbilityContainer.UpdateAbilitiesArray, which updates the visibility of the 'Call Skyranger' navigation help. As a result, the navigation help appears whenever Skyranger Evac is possible, although it does hide this information when the ability menu is raised so as …

Fix Controller Tactical Ability Selection + Add Commander Range function

---

LongWarOfTheChosen/Localization/LW_Overhaul.int
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIScreenListener_ViewObjectives.uc

LW2 attempted to add scrollbar support to objective descriptions through a screen listener which would create a custom `UITextContainer`; unfortunately, their method did not work and the objective description area could become an overlapping text mess.
Modifies : `UIScreenListener_ViewObjectives`
1.] For mouse and keyboard users :
- Scrollbars are enabled for the objective description text container via a Flash call to `EnableScrollbar`.
- Whenever an objective is chosen, via the objective list, scrolling is reset via a Flash call to `ResetScroll` and the scroll bar's slider position is reset via a Flash call to `SetThumbAtPercent`.
- A hidden panel is created and placed above the objective description's parent, `ItemCard`. Furthermore, it is set up to process the mouse events …

Fix the Objective Screen

---

LongWarOfTheChosen/Config/XComLW_UI.ini
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIScreenListener_UIStrategyMap.uc

Modifies : UIScreenListener_UIStrategyMap.uc
Controller users can now cycle through 'contacted' havens/regions on the strategy map using DPad left and DPad right. The following rules are followed :
1.] If a 'contacted' region is currently not selected, then a DPad press will select the starting region.
2.] If a 'contacted' region is currently selected, then DPad left will cycle 'contacted' regions from right to left. Although there is no way to define which regions are to the left/right of others, since this is based upon XComGameStateHistory's storage of outposts, selection order always remains consistent. During testing, this seemed to be a completely acceptable limitation, as map items can be cycled through quite quickly.
3.] If a 'contacted' region is currently selected, then DPad …

Allow Contacted Haven Cycling with Controller

---

LongWarOfTheChosen/Config/XComLW_OfficerPack.ini
LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/X2StrategyElement_LW_OTS_OfficerStaffSlot.uc

Added feature for better compatibility with mods like Playable Aliens and MEC Troopers, whose units shouldn't really be Officers due partly to missing animations.

Option to restrict more classes from officer training

---

LongWarOfTheChosen/Config/XComLW_UI.ini
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIScreenListener_SquadSelect_LW.uc

Provides 2 config variables which allow a controller user to hide the 1.] 'Save Squad' button and the 2.] Squad Container. These are turned OFF by default.
1.] The 'Save Squad' button appears while viewing a Long War squad's soldiers; controller users can not click it and, in fact, it appears not to 'do anything'.
2.] The 'Squad Container' allows mouse and keyboard users to perform squad selection on the Squad Select screen, as well as display the currently active squad. Once again, controller users can not click it, and my controller-capable Squad Management system - https://steamcommunity.com/sharedfiles/filedetails/?id=2314584410 - creates its own squad selection and display UI which overlaps with LW2's.
Both of these UI elements are created within …

Allow Hiding of 'Save Squad' button + Squad Container

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIOutpostManagement.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIResistanceManagement_LW.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIResistanceManagement_ListItem.uc

When viewing the strategy map, the X button brings up the Resistance Management screen. Consequently, I think it is more consistent if, while on the Resistance Management screen, the X button brings up the selected haven rather than the A button. Furthermore, it feels better if pressing the X button on a Haven screen modifies the haven adviser, rather than through right stick click.
Modifies : UIResistanceManagement_LW.uc
On the Resistance Management screen the A button sends the Avenger to the selected haven; formerly, this was attached to right stick click.
Modifies : UIResistanceManagement_ListItem.uc
On the Resistance Management screen the X button opens the corresponding haven screen; formerly, this was attached to the A …

Make Resistance/Outpost Screen controls a bit more consistent.

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIStrategyMapItem_Region_LW.uc

Adds part of the WOTC code related to displaying Chosen icons in UIStrategyMapItem_Region objects. As far as I can tell UpdateFlyoverText function of UIStrategyMapItem_Region_LW was copied from vanilla UIStrategyMapItem_Region pre-WOTC, and simply haven't been updated since.

Add Chosen icons to the regions

---

LongWarOfTheChosen/Src/LW_AlienPack_Integrated/Classes/X2Character_AlienPack.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_BiggestBooms_LW.uc

X2Effect_BiggestBooms_LW added check to prevent increasing damage for attacks with damage value of 0. However, AdvGrenadierM3, AdvRocketeerM3 and AdvMecArcherM2 were assigned original Biggest Booms ability, which didn't have that check and allowed them to sometimes damage normally immune targets (#999). This fixes it.
It is slight nerf to M3 Grenadiers and M3 Rocketeers, and buff to M2 Archers, since Biggest Booms didn't even work for them in the first place, as original effect checks for damage source to be bIndirectFire and Micro Missiles use standart targeting.
Additionally I have no idea why X2Effect_BiggestBooms_LW would return 1  if bIgnoreBaseDamage is set. Nothing else does this, and it directly contradicts what tooltip for Biggest Booms say (it should not affect Concussion Rocket …

Fix Biggest Booms bypassing Fortress/Bastion

---

LongWarOfTheChosen/Src/LW_AlienPack_Integrated/Classes/X2Character_AlienPack.uc

Unlike normal sectoid, sectoid commander template creation does not comment out DelayedPsiExplosion and SectoidDeathOverride abilities. These abilities seem to do nothing at all except panning camera on the Sectoid Comannder corpse two turns after his death.

Fix camera moving onto Sectoid Commander corpse

---

LongWarOfTheChosen/Config/XComLW_Overhaul.ini

This fixes #887 / #1037 issues of multiplying plasma grenase and nanomedikits.
For reference, upgrading occurs in X2StrategyElement_XpackStaffSlots.CheckToUpgradeItems.
There are different ways to fix this. The selected way of adding techs to SchematicsToDisable is roundabout one, and was chosen only because there is precedence of using it for AdvancedGrenades case already. But if it works it works I guess.
The alternative would be to clear BaseItem field for Nanomedikit and AlienGrenade templates, which makes somewhat more sense overall, since these items have different infinite/buildable status already. But I am not 100% sure what consequences clearing BaseItem would have, and there is comment at https://github.com/long-war-2/lwotc/blob/27ba49a62f93dfe96c8b5a17d584359cd6bd3d6d/LongWarOfT …

Fixing multiplying Plasma Grenades and Nanomedikits

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIMission_LWLaunchDelayedMission.uc

Simply updates Shadow Chamber information window after boosting infiltration, so you don't have to manually do this by going to the avenger and returning back.

Update Shadow Chamber information window after boosting infiltration

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_CoupDeGrace2.uc

If the target is both panicked and disoriented Coup De Grace currently gives halved bonuses for disorientation. It is counter-intuitive and I failed to see any practical reason for this behaviour, so this should change it.

Prioritize maximum bonus values for CoupDeGrace2

---

LongWarOfTheChosen/Config/XComLW_Overhaul.ini
LongWarOfTheChosen/Src/LW_Overhaul/Classes/CHItemSlot_PistolSlot_LW.uc

Adds a LWOTC_PISTOL_SLOT_WEAPON_CAT variable to add weapon categories assigned to eInvSlot_Pistol

Add the option to configure Pistol Slot weapons

---

LongWarOfTheChosen/Src/LW_Toolbox_Integrated/Classes/XComGameState_LWToolboxOptions.uc

Function ReleaseSoldierFromAlienHQ, added in "Attempt to fix issues with rescuing captured soldiers" commit, called ModifyStateObject with undefined AlienHQ, which caused following redscreen message in the log: "Redscreen: ModifyStateObject called with a specified ObjectID of '0' for class 'XComGameState_HeadquartersAlien'- this is an invalid argument!"
As far as I can tell, this caused this function to do nothing, which means soldiers captured status was not cleared. Adding the usual line for initializing AlienHQ fixed the "getting already rescued soldier as a reward" bug when I tested it. It might also be the cause of "getting empty soldier as a reward" bug, but I have not verified it, because unlike the previous bug I couldn't easily reproduce it.
Another thing to mention. I am not …

Possible fix to bugs with captured soldiers

---

LongWarOfTheChosen/Config/XComLW_Overhaul.ini
LongWarOfTheChosen/Src/LW_Overhaul/Classes/CHItemSlot_PistolSlot_LW.uc

1. Split the encounter lists for Leader and Follower (previously both drew from the same Encounter List)
2. Spectres, Archons and Sectoids can now spawn as Leaders and Followers
3. Vipers and Faceless can spawn as Followers
4. Muton Elites, Centurions, and Sectoid Commanders can spawn as Leaders
5. Officers and Priests now only spawn as Leaders
6. Trooper variants and Stun Lancers now only spawn as Followers (Sergeant included)

Added aliens to Rendezvous spawns

---

LongWarOfTheChosen/LongWarOfTheChosen.x2proj
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_TechnicalAbilitySet.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_BonusWeaponDOT.uc

Fire and Steel currently do not apply its bonus damage to burn tick damage, despite the description saying it should. The issue and the solution are the same as what was solved in "Make Boosted Cores apply to tick damage".
Since burning effect have bIgnoreBaseDamage flag set, the normal X2Effect_BonusWeaponDamage won't apply to it. X2Effect_BonusWeaponDOT copies the base functionality of X2Effect_BonusWeaponDamage with an option for it to apply to sources with bIgnoreBaseDamage set, such as DOT effects.

Fix Fire and Steel not applying to burn tick damage

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_DefaultAlienActivities.uc

This is the fix to the couple of problems with offworld reinforcements which were previously discussed.
Currently, it is possible for arriving alert points to be assigned to already liberated adjacent regions. Also, it was possible to get less alert points than intended, due to the fact that elements were removed from RegionLinks array, but RandIndex was determined by the length of different array.

Fixing the distribution of legions on Offworld Reniforcements

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_TechnicalAbilitySet.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Item_StingGrenade.uc

Currently, the Sting Grenades replacement items are created with their disorient and stun effects set to have "Mental" damage type (which is the default value of CreateDisorientedStatusEffect() and CreateStunnedStatusEffect() functions). This is unlike normal flashbang grenades, which are created without this damage type. Therefore, it leads to the situation where Grenadier who bought Sting Grenades perk suddenly can't disorient certain enemies which he previously could, for example Spectres.
This change make their sting grenades grenades consistent with flashbangs, if a bit stronger (which they probably did not need, but oh well).
As for the Concussion Rocket, it had only disorient effect created with default arguments, so you could stun but not disorient Spectres, for no apparent …

Remove "Mental" damage type from Sting Grenades and Concussion Rocket

---

LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Ability_PerkPackAbilitySet2.uc

Currently the interaction between Smoker/Flashbanger and Full Kit abilities depend on the order of which they were acquired. So, Full Kit is inconsistent in granting or not extra flashbang/smoke grenade. Additionally, per Full Kit description it is arguable that it should not apply to these extra grenades at all.
This changes priorities of Smoker/Flashbanger templates, so that they happen after Full Kit and therefore would not have extra charges.

Change priority of Flashbanger and Smoker templates

---

LongWarOfTheChosen/Config/XComAI.ini

- Movement profile used in FindLightningFieldDestination modified because FindRestrictedDestination-MWP_Standard was failing, causing Sectopod to not move for Lightning Field even when it could.
- TryMoveForLightningField given highest priority for movement in first and second AP. TryLightningField given highest priority in second and third AP. UnitValue used to ensure Lightning Field triggers only after successful TryMoveForLightningField check.
- TryMoveTowardVisibleEnemies50 behaviours removed because they called TryMoveForLightningField anyways, meaning they are made redundant by moving TryMoveForLightningField up.
Other changes
- Wrath Cannon checked only on last AP, ensures Sectopod can relocate for better opportunities first instead of being locked to spot.
- ShootIfAvailable …

Sectopod Lightning Field AI Fix & Priority Changes

---

LongWarOfTheChosen/Config/XComGameData_SoldierSkills.ini
LongWarOfTheChosen/LongWarOfTheChosen.x2proj
LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2Effect_Amplify_LW.uc
LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2Effect_Apotheosis.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_ApplyAltWeaponDamage.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_DefendingMeleeDamageModifier.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_GeneralDamageModifier.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_RoustDamage.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2LWAbilitiesModTemplate.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_AbilityDamageMult.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_AbsorptionFields.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_Brawler.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_DeadeyeDamage_LW.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_Formidable.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_IronCurtain.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_KillerInstinct.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_Mayhem.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_PCTDamageReduction.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_PrecisionShotCritDamage.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_WalkFireDamage.uc
LongWarOfTheChosen/Src/LW_XModBase/Classes/XMBEffect_ConditionalBonus.uc

This makes all %-based abilities in LWOTC use the new Community Highlander hooks that ensure they work reliably, applying percentage changes to all flat damage bonuses and penalties as well as being independent of effect order.
I also updated `X2Effect_ApplyAltWeaponDamage` so that it's inline with the latest CHL version of the base class. Ideally we would add an overridable function to the CHL base class that returns the base weapon damage. Then we could remove most of the code, but not ready to make another highlander change at this point.

Update effects for CHL damage modifier hooks

---

LongWarOfTheChosen/Config/XComGameBoard.ini
LongWarOfTheChosen/Localization/XComGame.int
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2LWCovertActionsModTemplate.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_DefaultCovertActions_LW.uc

I felt like we needed some more early covert actions to populate the pool, and Resistance MECs are neat, so why not?

Add a Covert Action to obtain a Resistance MEC

---

LongWarOfTheChosen/Config/XComAI.ini

Adds a check that makes Warlock only teleport units that have been engaged with XCOM for more than one turn. 
This prevents Warlock from wasting Teleport AP on units that were just summoned or dropped as reinforcement (and therefore cannot act after teleport).
Moved back TryChosenSummon to Child[0] since the issue that made it move to Child[4] was fixed.

Warlock Teleport AI Improvement

---

LongWarOfTheChosen/Config/XComAI.ini

Fixes the problem of Shieldbearer AI always using shield on its first turn no matter what, while keeping its defensive behaviour intact; shielding 3+ units are still prioritized highest, but high priority shots are checked before TryEnergyShieldOnAnyTarget

Shieldbearer AI modification

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIStrategyMapItem_AlienNetworkComponent_LW.uc

Modify `UIStrategyMapItem_AlienNetworkComponent_LW` so that Alien Facilities are clickable with a controller.
**Description** : A while back, `UIStrategyMapItem_Mission_LW `was modified so that strategy map items could be 'clicked' and would interact appropriately with a controller. Unfortunately, I didn't realize that the alien facility had its own special strategy map item class, `UIStrategyMapItem_AlienNetworkComponent_LW`.
Consequently, I have transferred all of the changes I made to `UIStrategyMapItem_Mission_LW` into `UIStrategyMapItem_AlienNetworkComponent_LW`.
Here is a general discussion of the changes made from my commits for `UIStrategyMapItem_Mission_LW`
=========================
Modifies `UIStrategyMapItem_AlienNetworkComponent_LW `--> `InitMapItem()`
When using a controller, …

Make Alien Facilities controller compatible

---

LongWarOfTheChosen/Localization/LW_Overhaul.int
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_StrategyMap.uc

Add Strategy Map 'Open Haven Management' and 'Open Resistance Management' `NavHelp` items when using a controller.
When on the strategy map, and using a controller either :
1. Display an 'Open Haven Management' `NavHelp` item if a haven is currently selected.
2. Display an 'Open Resistance Management' `NavHelp` item if a haven is not currently selected.
Adds : `X2EventListener_StrategyMap.DisplayResistanceAndHavenManagementNavHelp`
Whenever `UIStrategyMap.UpdateButtonHelp` is called to update the strategy map's button help bar, the event `StrategyMap_NavHelpUpdated` is triggered and, ultimately, `DisplayResistanceAndHavenManagementNavHelp` is called. `DisplayResistanceAndHavenManagementNavHelp` determines if the currently selected map item is a contacted haven or not, and adds the …

Add Strategy Map NavHelp items when using a controller.

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc

Currently Chosen can sometimes select uncontacted region as a target for their Retribution activity.
I am fairly sure that if you iterate over array in such order, while removing  elements from it, you will skip over some regions and thus allow some uncontacted regions into the deck. Iterating in inverse order should fix it.

Fix to Chosen selecting uncontacted regions for Retribution

---

LongWarOfTheChosen/Config/XComGameData_SoldierSkills.ini

No one bothered to add these two abilities to the exclusion list yet, so I might as well.
Indomitable should be removed because ghosts should not be able to raise their focus.
Terrorize should be removed because ghosts don't have Volt in the first place and so it is cleaner this way.

Remove Indomitable and Terrorize from templar's Ghosts

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_DefaultAlienActivities.uc

This clears job prohibitions and retributions affecting the region when the region is liberated. The ingame notification may occur slightly after, but you can start assigning rebels to the job immediately.
Was reported in #686.

Clear job prohibitions after liberation

---

LongWarOfTheChosen/Config/XComLW_OfficerPack.ini

So, it seems to me that Fire Discipline officer perk did absolutely nothing this whole time. Because FIREDISCIPLINE_REACTIONFIRE_BONUS value was assigned in the wrong section of the ini file, the value X2Effect_FireDiscpline used was 0. Fascinating.

Fix Fire Discipline

---

LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_KilledEnemy.uc

Currently Combat Rush effect from PCS can only be triggered by kills where there is "primary target". So, for example, if you kill an enemy using grenades, then it won't trigger. Most likely the cause of this: #1401.
For some reason current implementation tries to catch kills in PostAbilityCostPaid function. It seems weird when there are "UnitDied" and "KillMail" events already. Though, I am not sure what are the exact practical differences between the two.
This replaces PostAbilityCostPaid approach with KillMail listener. Note, that
BroadcastCombatRush still left with the trigger for 'CombatRush'-named  event, even though nothing call it now. I was not sure whether to remove it as obsolete, or to keep in case something else will try to use 'CombatRush' event.

Fix Combat Rush PCS

---

LongWarOfTheChosen/LongWarOfTheChosen.x2proj
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_GearAbilities.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_FlechetteRounds.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_StreetSweeper.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Item_LWUtilityItems.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_NeedleGrenades.uc

Currently Needle Grenades, Street Sweeper and Flechette Rounds won't apply to units whose armor was shredded.
Per discussion on the discord, I think it would be better to fix the effects, so that it would classify units with fully shredded armor as 'unarmored', as I think it is what most would expect of it.
For Needle Grenades and Street Sweeper the changes simply replace the armor check.
For Flechette Rounds I couldn't see how to easily fix the condition without creating new effect, so I created a new one, based on how stiletto rounds one was done.
One cosmetic difference to how it was previously done (and unlike how stiletto rounds is done) is not using additional PurePassive ability to display flechette rounds description, but displaying the existing effect itself. Which specifically …

Fix to the effects which check 'unarmored' status 

---

LongWarOfTheChosen/Config/XComGameData_SoldierSkills.ini
LongWarOfTheChosen/Config/XComLW_SoldierSkills.ini

The config change of setting InfiltrationHackBonus value to 0 was put in the wrong ini file and does not take the effect.
A trivial fix, which you even might have made locally already. It is here mainly in case its issue was accidentally skipped over and so to not be forgotten about.

Fix to InfiltrationHackBonus change

---

LongWarOfTheChosen/Config/XComClassData.ini
LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/XComGame.int
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_LockedOn.uc

Currently ranger's Locked On effect is lost when using any non-offensive ability or using non-primary weapon. This behavior differs from original LW2 and, I think, feels very janky.
From what I can tell, here is how it happened. Originally Locked On relied on XComGameState_Effect_LastShotDetails class to keep track of who was shot last. However, this class' event listener does not make the check that the unit using an ability is the same as the unit which have relevant effect (which is unclear as to why for me, but I suspect it is either the difference in how it is triggered in vanilla or how it was subscribed to in LW2).  Which lead to there being an issue where locked on was cleared by other soldiers using their abilities. That issue was fixed there #621 by replacing Locked On listener …

Make Locked On not lose the bonus on non-offensive abilities

---

LongWarOfTheChosen/Localization/XComGame.int
LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_DefaultAbilitySet.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc

Certain enemy types have a chance to resist disorientation from flashbang grenades, which is defined by ENEMY_FLASHBANG_RESIST array. However, apart from a vague and brief mention in flashbang grenades description, players have no way of knowing about existence of such a mechanic and it can (and does) lead to confusing gameplay moments.
This change add a passive ability to relevant enemy types which provide information about this innate property in its description. The ability itself is purely cosmetic, as the resistance code is integrated into flashbang grenades themselves.
I added ability template creation into X2Ability_LW_DefaultAbilitySet because I couldn't find more appropriate class to add it to, and creating a new one felt like overcomplication. But it being in …

Add passive ability describing ENEMY_FLASHBANG_RESIST mechanic

---

LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/X2Ability_OfficerAbilitySet.uc

MaxOfficerRank config variable is inclusive, so the iterating cycles using it should be as well. Right now at the latest officer rank Command Range ability shows missing text error and won't increase its radius, compared to Command Range 6. Loc strings for Command Range 7 already exists, but  simply were not used. This change fixes it.

Fix to "Command Range 7" ability

---

LongWarOfTheChosen/Config/XComLW_Overhaul.ini

Simple fix to Double Tap ability.
Classes other than Sharpshooter can get Double Tap ability with XCom row, but they won't be able to use it for overwatching despite the description explicitly saying they should be able to. Normal 'Overwatch' ability isn't on the list of allowed abilities which you can spend bonus action point on (only SniperRifleOverwatch is). This fixes it.

Add Overwatch to the DoubleTapAbilities whitelist

---

LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/X2Ability_OfficerAbilitySet.uc
LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/X2Ability_OfficerAbilitySet_PassiveAuras.uc

This is the fix similar to what was done for Field Surgeon there: https://github.com/long-war-2/lwotc/pull/1273. It seems that change works fine enough, so I decided to fix other similar abilities as well.
To reiterate, "aura"-type abilities which apply to all allies and rely on UnitPostBeginPlayTrigger do not work on liaisons (and most probably on other units which come into play later in the mission, like avenger defense reinforcements). These abilities are: Esprit de Corps, Defilade,, Fire Discipline and Combined Arms. This change make these abilities to rely on OnUnitBeginPlay trigger, which would trigger for any unit entering tactical at any time, and subsequently apply its corresponding effect to said unit.
The changes were tested in the haven retaliation mission. These effects were …

Make officers' aura abilities apply to liaisons

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_ChosenAbilities.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Action_Fire_ChainLightning.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_KilledEnemy.uc

Removed couple of unused local variables. Renamed formerly private variables in X2Action_Fire_ChainLightning so that those no longer "conflicts with previously defined field" with private versions in X2Action_Fire.

Fixing compiler warnings

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/XComGameState_LWOutpost.uc

Since both GetNumFaceless() and GetRebelCount() function results are of "int" type the division applied is here is the integer division. So, GetNumFaceless() / GetRebelCount() can only be equal 1 if all rebels are faceless and 0 otherwise. Thus, this part of the check will always pass if there is at least one non-faceless rebel in the haven, and so MAX_FACELESS_PROPORTION being set to 0.32f is meaningless, as it could  have been set to 0.99f with the same effect.
Casting function results to float should fix it.
This change does affect strategic layer. Players could previously get havens with like 4/5 faceless, which would no longer be possible with this change.  As I understand there is certain hesitance to change strategic layer, so  I leave the decision to whether fix it or not to …

Fix MAX_FACELESS_PROPORTION check

---

LongWarOfTheChosen/Config/XComLW_OfficerPack.ini

Currently, SPARKs' main weapon attacks get bonus aim from already applied stacks of Focus Fire, but do not contribute to it. Adding 'sparkrifle' to Focus Fire VALIDWEAPONCATEGORIES list make SPARKs fully benefit from Focus Fire.
It may be argued, that it should be made that the SPARKs do not get _any_ Focus Fire benefits, including the aim, due to how officer abilities generally do not apply to SPARKs (with couple exceptions). However, making both parts works is an easier fix to do, so I chose this approach.

Fix Focus Fire inconsistent applicability for SPARKS

---

LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/X2Ability_OfficerAbilitySet.uc

Currently, if you use Jammer ability, save the game, then reload it, Jammer charges will be restored.
Adding this line (taken from TypicalAbility_BuildGameState) fixes it.

Fix Jammer charges persistence

---

LongWarOfTheChosen/Localization/LW_FactionBalance/XComGame.fra
LongWarOfTheChosen/Localization/LW_FactionBalance/XComGame.rus

Fixed Russian and French descriptions of Overcharge incorrectly mentioning defence bonus instead of crit bonus.

Overcharge localization fixes

---

LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_TrojanVirus.uc

Related to https://github.com/long-war-2/lwotc/issues/1491.
Currently, Trojan damage rolls use soldier's raw hacking stat without accounting for bonuses to Hack from gremlin/skulljack.
This may or may not have been intended. Personally, I find it non-intuitive, thus proposing this change. It does buff trojan average damage considerably though.

Change Trojan damage to account for items' Hack bonuses

---

LongWarOfTheChosen/Localization/XComGame.int

Blinding Protocol's LocLongDescription wasn't quoted. This didn't seem to break anything, but here we go.
Found by mrvecs
https://discord.com/channels/590853492084572170/690570972117336064/1156933998229065789

Quote Blinding Protocol's LocLongDescription

---

LongWarOfTheChosen/Localization/XComGame.int

Darklance has had a standard reload for a long time, TacticalText was misleading.
Found by Rifleman
https://discord.com/channels/590853492084572170/690570972117336064/1158295652791496726

Edit Darklance's TacticalText to not include mention of complex reload

---

LongWarOfTheChosen/Config/XComLW_Overhaul.ini

Includes abilities that (currently) don't appear on classes that can get Double Tap. It's future proofing / being mod friendly.

Expand list of abilities usable after Double Tap

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Ability_PerkPackAbilitySet2.uc

* Fix SPARK BIT dodge being labeled in English even when playing in another language
* Fix SPARK Reboot stat labels (even though they don't seem to appear anywhere)

SPARK stat label localizations

---

LongWarOfTheChosen/Localization/XComGame.chn
LongWarOfTheChosen/Localization/XComGame.cht
LongWarOfTheChosen/Localization/XComGame.deu
LongWarOfTheChosen/Localization/XComGame.esn
LongWarOfTheChosen/Localization/XComGame.fra
LongWarOfTheChosen/Localization/XComGame.int
LongWarOfTheChosen/Localization/XComGame.ita
LongWarOfTheChosen/Localization/XComGame.jpn
LongWarOfTheChosen/Localization/XComGame.kor
LongWarOfTheChosen/Localization/XComGame.pol
LongWarOfTheChosen/Localization/XComGame.rus
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_Soldiers.uc

The Covert Action for training that boosts attributes by spending AP does not display a name in the soldier list, and the time always shows as 0 without changing until the mission is completed.
After analysis and testing, it appears that the reason may be the absence of 'BonusText' in the CovertActionIntenseTrainingStaffSlot. It seems that adding 'BonusText' to the translation file should resolve the display issue.

Fix covert action display

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc

CBAC no longer ships with the config that forces Whiplash to be 0AP, we can revert our bandaid.

Revert Whiplash CBAC bandaid fix

---

LongWarOfTheChosen/Config/XComGame.ini

Moving RJSS in run order to last fixes attachment icons, because LWOTC creates more attachments (for lasers and coils) after RJSS is done changing their icons.

Fix attachment icons

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2LWAbilitiesModTemplate.uc

According to localization, Revival Protocol only removes mental impairments. What it doesn't tell you is that it also cures those statuses that a medkit would. However, being afflicted by those statuses doesn't make a unit an eligible target for Revival Protocol.
PR changes Revival Protocol to only cure mental impairments, as that's the intended effect (based on Firaxis' localization).

Only remove mental impairments with Revival Protocol

---

LongWarOfTheChosen/Localization/XComGame.int

Same as #1719, but for abilities. The text for Officer/Priest variant seems to be omitted in base game, not going to bother with that one.

Use "attacks" instead of "fire" in Return Fire ability loc

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2LWActivityCondition_MinRebels.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_DefaultAlienActivities.uc

This adds the min haven count condition to the invasion activity similar to haven retaliations so that there are still some rebels that can be rescued. This should help resolve [Invasions with 0 rebels](https://github.com/long-war-2/lwotc/issues/1547) that just ends up in an automatic failure as there was no one to rescue.
Currently just using the haven retaliation count as it made the most sense to keep the two the same. 
Also updated the logging for "MinRebel" to make it clear whether the activity can launch in a given region.

add min haven count to invasion activity 

---

LongWarOfTheChosen/Localization/XComGame.chn
LongWarOfTheChosen/Localization/XComGame.cht
LongWarOfTheChosen/Localization/XComGame.deu
LongWarOfTheChosen/Localization/XComGame.esn
LongWarOfTheChosen/Localization/XComGame.fra
LongWarOfTheChosen/Localization/XComGame.int
LongWarOfTheChosen/Localization/XComGame.pol
LongWarOfTheChosen/Localization/XComGame.rus
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Ability_XMBPerkAbilitySet.uc

Create a copy of Lightning Slash that's only usable with one action left, has no movement range modifier, and shares cooldown with the regular Lightning Slash. Basically the same as what was done to a couple of special shots to work with Snap Shot.

Allow Lightning Slash with last action

---

LongWarOfTheChosen/Localization/XComGame.int

Specifically, add the recently discovered fact that you can only parry one melee attack per turn. It was also due for a reword.

Update Combatives loc

---

LongWarOfTheChosen/Localization/LW_FactionBalance/XComGame.int
LongWarOfTheChosen/Localization/XComGame.int
LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2Ability_ReaperAbilitySet_LW.uc
LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2DownloadableContentInfo_LW_FactionBalance.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_AssaultAbilitySet.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_DefaultAbilitySet.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_TechnicalAbilitySet.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_TheLost_LW.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Character_TheLost_LW.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc

* Arc Thrower, Arc Pulser, Chain Lightning and Disabling Shot can now target Psi Zombies and Avatars -- they're still immune though
* Modify Concussion Rocket to deal damage to everyone in the AoE, including robots and friendlies, and impair all organics
* List immunities in F1 for Psi Zombie, Spectral Zombie and The Lost
Updated localizations:
* Concussion Rocket
* Chain Lightning
* Disabling Shot
* Solace and Solace Aura
* Chosen Immunities
Updated soldier speeches:
* Concussion Rocket now uses `RocketLauncher` (was `Explosion`, which is unused)
* Disabling Shot now uses `StunTarget` (same as Arc Thrower's - was `Reaper`)

Various impairment standardizations

---

LongWarOfTheChosen/Localization/LW_AlienPack_Integrated/XComGame.int

Rename some ADVENT units to be more in Firaxis style:
* Units in the same lineage share a part of the name
* Only the first tier of a unit starts with "ADVENT"
* The top tier of a unit is called "Elite"
The following only lose the preceding "ADVENT":
| Before | After
|-|-|
| ADVENT Hunter Drone | Hunter Drone
| ADVENT Heavy Gunner | Heavy Gunner
| ADVENT Elite Gunner | Elite Gunner
| ADVENT Heavy Rocketeer | Heavy Rocketeer
| ADVENT Elite Rocketeer | Elite Rocketeer
| ADVENT First Sergeant | First Sergeant
The following have had their names changed to emphasize their place in a lineage of units:
| Before | After
|-|-|
| ADVENT Guardian | Advanced Sentry
| ADVENT Sentinel | Elite Sentry
| ADVENT Heavy Grenadier | Elite Grenadier
| ADVENT General (M2) | Elite General …

ADVENT unit name normalization

---

LongWarOfTheChosen/Config/XComGameData.ini

the last 10% of wound time setting has a range of 30k to heal vs the other intervals which have a standard of a 7.5k range. Most soldier's will never reach this interval and for those that do can end up with unnecessarily long wounds if they get gravely wounded and makes it up in the air to RNG which isn't great. This can also in a sense make more HP worse if you do get to this wound interval which is counterpoint to having more HP that should be making them more overall healthier than those with low HP. 
This change sets it so that the range is 7.5k like the rest of the wound settings dropping the max wound healing time to be 52.5k (except for rookie which is set to still be lower than other difficulties).

Normalize wound at end

---

LongWarOfTheChosen/Localization/XComGame.int
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_ChosenAbilities.uc

it no longer grants bonus shields, the extra shields was a lot of extra effective hp added to the chosen that was re-usable so it felt unfair

Nerf unholyascension

---

LongWarOfTheChosen/Localization/XComGame.int

LTT now uses weapon default action cost, so it's implied

Remove mention of action cost in LTT

---

LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/XComGame.int

Removing redundant text fixes formatting.

Reduce repetition in Hard Target loc

---

LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/XComGame.int
LongWarOfTheChosen/Localization/XComGame.int

Multiple localization edits, mostly reducing redundant text in promotion popups, but also mechanic corrections and typo fixes.
Affected perks:
* Hard Target
* Infighter
* Aggression
* Cool Under Pressure
* Scrap Metal
* Rapid Reaction
* Lock 'n Load
* Paramedic
* Executioner
* Open Fire
* Combat Fitness
* Close and Personal

Multiple localization edits

---

LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_MovingTarget_LW.uc

The recent fix to Moving Target accidentally set the defense and dodge values to 0.
MT_DEFENSE and MT_DODGE were changed from config variables to simple instance variables in 0ef85b2db, so the default property value of these variables is zero.

Use the local value of MT_DEFENSE and MT_DODGE in X2Effect_MovingTarget

---

LongWarOfTheChosen/Src/PI_Integrated/Classes/XCom_Perfect_Information_UIScreenListener.uc

The damage breakdown in the ShotHUD wings is missing and has been missing since WOTC.
We cannot delete the PI_Integrated mod because it contains a copy of Grimy's shot bar code that shows crit/graze breakdown, but we can at least restore the damage breakdown for the user by using the default shotwings object.
Current LWOTC shotwings with missing damage breakdown:
LWOTC with default shotwings object (this PR):
For comparison, here is the regular shothud:
And LWOTC + [WOTC] Extended Information:

Fix broken ShotHUD by disabling shotwings from PI_INTEGRATED

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_ChosenLoot.uc

Use of an uninitialized variable. We can make guesses about why this crashes on Linux and not on Windows, but this is a code error on Windows as well.
Fixes https://github.com/long-war-2/lwotc/issues/1624

Fix crash on Linux on killing a Chosen

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc
LongWarOfTheChosen/Src/LW_Toolbox_Integrated/Classes/X2DownloadableContentInfo_LWToolbox.uc

Some of the template modifications made by LW_Toolbox run at OnLoadedSavedGameToStrategy because it requires some settings recorded to its XGS. The modification of RewardTemplates is implemented in a static function that doesn't refer to the XGS and should probably be moved to OPTC. I'll hopefully be moving it to the proper time so other mods can overwrite it with the proper CHL run order. Fixes Issue #1807

RewardTemplates being modified after OPTC

---

LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Ability_PerkPackAbilitySet2.uc

Another small thing that bothered me. If the aliens shot your hacked robot dead there was still a "Trojan Virus" flyover.

Trojan Flyover Nitpick - Skip if the unit has died to unrelated causes

---

LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_Aggression.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_Executioner_LW.uc

Allow Aggression and Executioner bonuses to apply to any ability instead of requiring the ability to be bound to any weapon. Relevant for any ability that doesn't require a weapon to work.

Remove weapon check for Aggression and Executioner

---

.gitmodules
.scripts/build.ps1

⚠️ Mostly untested change, test PR locally before merging ⚠️ 
The PR removes the very outdated CHL submodule, which shouldn't have any part in the build process - yet it did build for me, interfering with the up-to-date CHL in SDK's `SrcOrig`. Also removes the line in `build.ps1` that refers to the now nonexistent directory.
Consider also updating the steps referring to CHL in README's build instructions.

Remove CHL submodule and corresponding line in `build.ps1`

---

LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIScreenListener_ArmoryWeaponUpgrade_LW.uc

The original code checked specifically for _eInvSlot\_PrimaryWeapon_, as well as making use of _ItemState.HasBeenModified()_ that checks for stuff other than the presence of upgrades on the weapon. This should streamline the stripping process and actually work for Primary Secondaries that have been upgraded.

Generalizing check for stripping unequipped weapons of their upgrades

---

LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2Ability_ReaperAbilitySet_LW.uc

Move the stun effect before the damage effect to make the stun come earlier in the visualization tree, preventing the damage flinch action.

Change the order of effects in Disabling Shot

---

LongWarOfTheChosen/Localization/XComGame.int

Change the tag to LW's one that pulls the name of the bound weapon.

Fix weapon name for Bladestorm

---

LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2Effect_DeathDealer_LW.uc

Based on Hit and Run and other abilities that work during Green Alert, fixed Death Dealer's doubled crit damage not applying during Green Alert.

Fixed Death Dealer's doubled crit damage not applying during Green Alert

---

LongWarOfTheChosen/Localization/XComGame.chn
LongWarOfTheChosen/Localization/XComGame.cht
LongWarOfTheChosen/Localization/XComGame.deu
LongWarOfTheChosen/Localization/XComGame.esn
LongWarOfTheChosen/Localization/XComGame.fra
LongWarOfTheChosen/Localization/XComGame.int
LongWarOfTheChosen/Localization/XComGame.pol
LongWarOfTheChosen/Localization/XComGame.rus
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc
LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2LWAbilitiesModTemplate.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_MeleeDamageResistance.uc

1. Add flags to enable / disable the melee DR effect from applying while burning, panicked, impaired, or frozen.
2. Disable Anticipation while the unit is panicked, frozen, or impaired.
3. Add localization tag for Anticipation DR.

Add unit conditions to Anticipation

---

LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Ability_XMBPerkAbilitySet.uc

1. Revalidate Zone of Control when a unit is mind controlled.
2. Revalidate Zone of Control when the effect is removed due to the source's death.

Update Zone of Control handling

---

LongWarOfTheChosen/Config/XComSchedules.ini

Removed 2 chryssalids off rookie and vet psi gate schedules and replaced with codex guards (2 codices)

Add 2 Codices to Psi Gate on Rookie and Veteran

---

LongWarOfTheChosen/Localization/XComGame.int
LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2Effect_BloodTrail_LW.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_BonusRocketDamage_LW.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_GrenadeDamage.uc
LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_NeedleGrenades.uc

1. Add missing `LocLongDescription`, `LocHelpText` and `LocPromotionPopupText` to `WatchThemRun_LW`.
2. Change `bDisplayInSpecialDamageMessageUI` for some effects to `false`.

Minor localization fixes
