long-war-2/lwotc

- LongWarOfTheChosen/Config/XComLW_Overhaul.ini
- LongWarOfTheChosen/LongWarOfTheChosen.x2proj
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWDLCHelpers.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc
Fix SPARK tech upgrades via WOTC integrated DLC helper class instead of LW2DLCHelper
Fixes #203.
> Fix SPARK tech upgrades

- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_StrategyMap.uc
Add an event listener that utilizes an event hook that listens for an
event fired whenever doom is updated. The event listener adds up all
of the doom for any facilities that have not been revealed and adds
that to all of the doom that has currently been gathered so that the
amount of doom is updated properly. The issue before this was that
alien facilities that were not revealed had an issue when updating doom
in that when they added a point of doom that point would be removed
then added which would make it look like it did not move up at all but
then when the facility was revealed it would add up all of the doom
that the facility had actually added.
> Add event listener for avatar project progress

- README.md
The link to the wiki to install was broken
> Fix broken link in Readme.md

- LongWarOfTheChosen/Config/XComClassData.ini
> #580 Remove Deadeye from Reaper's Random Abilities

- LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/XComGame.int
Update XComGame.int Skirmisher Body Shield Fixes #549
> Update XComGame.int Skirmisher Body Shield Fixes #549

- LongWarOfTheChosen/Localization/XComGame.int
Here we go!
In the TLE, one of the new shotguns is named "Scattergun," so I changed the coil shotgun to "Gauss Shotgun" to differentiate.
> Change Scattergun To Gauss Scattergun Text #579

- LongWarOfTheChosen/Localization/XComGame.int
In the dark event window, the "Hard Target" doesn't have any text, so I added text to it. 
Hopefully I did my best acting Shen's character!
> Added Quote for Hard Target Dark Event #559

- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_LockedOn.uc
Fixed issue where Locked On bonus was being lost if another shot was taken in between the Locked On soldier's shots. Closes #576
> #576 Fixed issue where Locked On bonus was being lost

- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc
> Give Sectopods Resilience

- LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2DownloadableContentInfo_LW_FactionBalance.uc
Allows Faction Soldiers to go on Combat Intelligence Covert Actions
Copy pasted Robojumper's code, slightly modified it to be prettier
> #728 Allow Faction Soldiers to go on CICA

- LongWarOfTheChosen/Localization/XComGame.int
Removed ", improving even further with proximity to the target" from laser sight descriptions to match their new functionality.
> Laser Sight Localization Fix

- LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2DownloadableContentInfo_LW_FactionBalance.uc
#685 Reupload from the previous PR (with the issue already adressed)
> #685 Allow Two Soldiers from each faction

- README.md
Now you can open the install page and still have a spare action left to hunker down.
> Update install wiki link in README

- LongWarOfTheChosen/Localization/LW_LaserPack_Integrated/XComGame.int
- LongWarOfTheChosen/Localization/XComGame.int
Just some stuff that bugged me, and i wanted to bring in some creative writing,
> Loc improvements

- LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIMission_LWLaunchDelayedMission.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIStrategyMapItem_Mission_LW.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIUtilities_LW.uc
This also allows mouse and keyboard users to use the arrow keys to select infiltration options and the spacebar / enter keys to "click".
-----------------------------------------
Modifies UIUtilities_LW --> BuildMissionInfoPanel().
When you click on a mission which is being infiltrated the infiltration screen, UIMission_LWLaunchDelayedMission, pops up. The function BuildMissionInfoPanel() creates the special mission information panel seen near the top of this screen. The problem is that within this function, a UIPanel and UIX2PanelHeader are created; however, they are never removed from the navigation system and end up causing problems with controller and arrow key navigation. Consequently, bIsNavigable has been set to false for both of them so they are no longer added to the navigation …
> Fix for #961 - Controller can't select infiltration options.

- LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIOutpostManagement_ListItem.uc
Makes UIOutpostManagement_ListItem compatible with RoboJumper's Rebel Job Selector.
The following changes were made :
1.] JobHeaderX and JobHeaderWidth are now set again, within UIOutpostManagement_ListItem --> BuildItem(), since Robojumpers Rebel Job Selector makes use of them.
2.] Robojumpers Rebel Job Selector relies upon SetJobName() being called; however, in several instances this was no longer the case. Rather than setting the job name manually, I now feed the name back into SetJobName().
There has also been a bit of code cleanup - the job name for mouse & keyboard users is set in UpdateStaticData() since it does not change colour and only needs to be set once. The job name for controller users is still set in UpdateDynamicData() since it needs to be modified when a list item …
> Make UIOutpostManagement_ListItem compatible with RoboJumper's Rebel Job Selector.

- LongWarOfTheChosen/Src/NewPromotionScreenByDefault_Integrated/Classes/NPSBDP_UIArmory_PromotionHero.uc
Modifies : NPSBDP_UIArmory_PromotionHero --> ChangeSelectedColumn
Beforehand, controller navigation of the promotion screen was not ideal; whenever column selection was changed, the 1st row of the new column was selected regardless of the previous column's row selection. Now there is an attempt to maintain the current 'row selection' when selecting different columns; if this is not possible, due to different column sizes, the closest possible row is selected.
----------------------------
Modifies : NPSBDP_UIArmory_PromotionHero --> ConfirmAbilityCallbackWithTracking
Originally, an ability's focus was lost upon being selected, due to the promotion data being re-populated. This has now been fixed.
----------------------------
Modifies : NPSBDP_UIArmory_PromotionHero --> InitPromotion
For …
> Improve New Promotion Screen controller compatibility + a few related fixes

- LongWarOfTheChosen/Config/XComAI.ini
One thing to note is that Assassin only seem to make single action when stealthed regardless of available AP (and somehow returns both NotLastActionPoint and IsLastActionPoint as true). I've built ChosenAssassinStealthBranch to work for both single-action and double-action version of Assassin regardless, in case debugger is wrong or you wish to change aforementioned behaviour.
> Chosen AI fix and improvement

- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/XComGameState_LWAlienActivityManager.uc
This is an attempt to fix the Chosen appearing on the wrong missions due
to vanilla modifying the tactical gameplay tags. The alien activity
manager now adds custom LWOTC tags that vanilla won't overwrite, and
then the `OnPreMission()` hook converts those to the corresponding
vanilla tags.
> Fix Chosen appearing on wrong missions

- LongWarOfTheChosen/Config/XComClassData.ini
Replaced Skirmisher's Implacable at XCOM T4 with InTheZone, deleted Reaper's duplicate FullKit ability, and fixed a bunch of ApplyToWeaponSlot stuff.
> Fixing a bunch of ClassData errors

- LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIPersonnel_SoldierListItem_LW.uc
UIPersonnel_SoldierListItem_LW is a UIButton, and ultimately a UIPanel.
UIPanel's bIsFocused is updated whenever a UIPanel recieves focus, via OnReceiveFocus, or loses focus, via OnLoseFocus. Consequently :
1.] UIPersonnel_SoldierListItem_LW.UpdateItemsForFocus's parameter, Focussed, is unnecessary.
2.] The boolean variable bIsFocussed, within UIPersonnel_SoldierListItem_LW, is unnecessary.
Just as a reminder, within OnReceiveFocus and OnLoseFocus, it is important to call their super variant, super.OnReceiveFocus or super.OnLoseFocus, before UpdateItemsForFocus. This is because UpdateItemsForFocus makes use of a UIPanel's focus status, defined by bIsFocused and updated via UIPanel.OnReceiveFocus and UIPanel.OnLoseFocus. Originally, within LW2, …
> Clean up UIPersonnel_SoldierListItem_LW Focus and Disabled Code

- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Ability_PerkPackAbilitySet2.uc
Currently Field Surgeon effect does not get applied to liaison (or rebels for that matter) on retaliation missions. This happen because Field Surgeon relies on UnitPostBeginPlayTrigger to apply its effect on all allies. And the liaison and rebels get added onto the map after that. (The relevant order of things are in X2TacticalGameRuleset.BeginTacticalPlay() function: first it applies UnitPostBeginPlayTrigger for all abilities, and then triggers OnTacticalBeginPlay event which LW2 code subscribe to to get liaison added).
This changes Field Surgeon effect to use OnUnitBeginPlay event to apply X2Effect_FieldSurgeon. on all relevant units. I have to admit that it took me an embarassing amount of time to get it working as it should. And even now I am not fully sure I've done it the proper way …
> Make Field Surgeon apply to liaisons

- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_FieldSurgeon.uc
Current description of Field Surgeon says: "It does not affect soldiers who suffered killing wounds and are stabilized from bleeding out.". However, it is erroneus for several reasons:
1. The code in X2Effect_FieldSurgeon checks only for BleedingOut status and not for Unconscious for target soldier.
2. BleedingOut status would be explicitly cleared prior to the Field Surgeon checks, if the soldier was carried out by someone else during evacuation (which is often the case).
3. Most importantly, both BleedingOut and Unconscious effects are cleared when the unit leaves play, which is way before Field Surgeon checks happen.
This changes X2Effect_FieldSurgeon effect to store the fact that soldier was bleeding out during any point of the mission and use this knowledge later to check whether …
> Prevent Field Surgeon to apply to bleeding out soldiers

- LongWarOfTheChosen/Src/LW_Toolbox_Integrated/Classes/UIOptionsPCScreen_LW.uc
Modifies : `UIOptionsPCScreen_LW`
Long War overrides the options screen, `UIOptionsPCScreen`, with `UIOptionsPCScreen_LW`; this affects both the main menu options screen as well as the in-campaign options screen.
Now :
1. When viewing the main menu options screen, Long War continues to make use of 5 conventional, Flash-defined, options tabs.
2. When viewing the in-campaign options screen, Long War disconnects the 5 conventional, Flash-defined, options tabs and makes use of its own `UIList`, `TabList`, instead.
Unfortunately, `SetSelectedTab` didn't take into account the substitution of `TabList` for the Flash-defined options tabs, when viewing the options screen 'in game'. Therefore, it would remove and add focus to the Flash-defined options tabs even when they were no longer being used. …
> Fix Options screen tab selection with controller

- LongWarOfTheChosen/Localization/LW_FactionBalance/LW_FactionBalance.fra
- LongWarOfTheChosen/Localization/LW_FactionBalance/XComGame.fra
- LongWarOfTheChosen/Localization/LW_Overhaul.fra
- LongWarOfTheChosen/Localization/XComGame.fra
> Update FRA - Make further faction soldier balance changes

- LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/X2DownloadableContentInfo_LWOfficerPack.uc
Currently it is possible to have two officers at the same time on certain type of missions. Namely the missions where some units are deployed later on: avenger defenses (reinforcements), any type of retaliations (liaisons) and ambushes (covert op team). If any of those later deployed units have an officer rank higher than the officer in the original team then they both will have access to officer abilities. It happens because the check IsHighestRankOfficerInSquad() for the officer in the original squad couldn't possibly take into account units not on the mission yet.
There are two possible views on how it could be fixed:
First one is to enforce "highest ranked officer present is the commanding one" idea. It would imply removing officer abilities from previous officer when a higher ranked …
> Fix double officers on certain missions

- LongWarOfTheChosen/Config/XComGameData_WeaponData.ini
Buff to XCOM Katana as discussed in https://discord.com/channels/590853492084572170/675330454554935306/934417323694120991
> Katana buff

- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWDLCHelpers.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc
Watch this break the steam realease
> Implement Rusty's Compatibility changes

- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWDLCHelpers.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIOutpostManagement.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_DefaultStaffSlots_LW.uc
> Lwotc 104 bugfixes

- .scripts/X2ModBuildCommon/CHANGELOG.md
- .scripts/X2ModBuildCommon/README.md
- .scripts/X2ModBuildCommon/build_common.ps1
- .scripts/X2ModBuildCommon/clean.ps1
- .scripts/X2ModBuildCommon/clean_cooker_output.ps1
- LongWarOfTheChosen/ContentOptions.json
- LongWarOfTheChosen/LongWarOfTheChosen-Stable.code-workspace
- LongWarOfTheChosen/LongWarOfTheChosen.x2proj
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc
Pulling out the massive oversized cartoon cannon (aka cooking the package)
> Banish Black Muton Elites to the shadow realm

- LongWarOfTheChosen/Config/XComWOTC_DisplayHitChance_MCM_Defaults.ini
- LongWarOfTheChosen/LongWarOfTheChosen.x2proj
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc
- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Ability_PerkPackAbilitySet.uc
> More bugfixes

- .gitignore
- LongWarOfTheChosen/Src/LWUtilities/Classes/Helpers_LW.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_DefaultAbilitySet.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Character_TheLost_LW.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_SmokeFlankingCritProtection.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_Soldiers.uc
Reverts long-war-2/lwotc#1605
Broke grenade icons with some Git refactoring, working on this separately now.
> Revert "Lwotc 104 bugfixes"

- LongWarOfTheChosen/Src/LWUtilities/Classes/Helpers_LW.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_DefaultAbilitySet.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Character_TheLost_LW.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_SmokeFlankingCritProtection.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2EventListener_Soldiers.uc
> Cache mod loading instead of calling it in hot code

- LongWarOfTheChosen/Config/XComMaps.ini
- LongWarOfTheChosen/Localization/XComGame.int
- LongWarOfTheChosen/Src/LW_FactionBalance/Classes/X2DownloadableContentInfo_LW_FactionBalance.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWVersion.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_ChosenAbilities.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_DefaultCovertActions_LW.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/XComGameState_LWAlienActivityManager.uc
Fix bugs reported with 1.1.0 Steam so far.
> Hotfix commits

- LongWarOfTheChosen/Src/LW_OfficerPack_Integrated/Classes/X2Ability_OfficerAbilitySet.uc
you still need bonus actions to do it anyways.
> Allow using Command while hunkered

- LongWarOfTheChosen/Localization/XComGame.int
Fixes #418, even though the continent bonus has been disabled, lol. Lmao, even.
> Fix Live Fire Training loc

- LongWarOfTheChosen/Localization/XComGame.int
Just a minor fix in configs for consistency
> Add missing equality signs

- LongWarOfTheChosen/Config/XComGameData.ini
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTemplateMods.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_PsiOperativeAbilitySet.uc
slight buff to psi ops,
slightly lower promotion training as the early rank perks tends to extend training time quite a bit
swapped some of the pre-requisites around to make the weaker picks unlock more better perks
> Psi ops changes

- LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/XComGame.int
> Rename base game Ranger slash

- LongWarOfTheChosen/Localization/LW_FactionBalance/XComGame.chn
- LongWarOfTheChosen/Localization/LW_FactionBalance/XComGame.cht
- LongWarOfTheChosen/Localization/LW_Overhaul.chn
- LongWarOfTheChosen/Localization/LW_Overhaul.cht
- LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/LW_PerkPack_Integrated.chn
- LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/LW_PerkPack_Integrated.cht
- LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/LW_PerkPack_Integrated.int
- LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/XComGame.chn
- LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/XComGame.cht
- LongWarOfTheChosen/Localization/LW_WeaponsAndArmor/XComGame.chn
- LongWarOfTheChosen/Localization/LW_WeaponsAndArmor/XComGame.cht
- LongWarOfTheChosen/Localization/XComGame.chn
- LongWarOfTheChosen/Localization/XComGame.cht
- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_RepairArmor_LW.uc
1.Optimize the Chinese translations for some abilities, items, and tips.
2.Complete the translatable content for Spark's repair ability
> Optimize some Chinese translations

- LongWarOfTheChosen/Config/XComLW_SoldierSkills.ini
- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Ability_XMBPerkAbilitySet.uc
changes the ability list to trigger lick your wounds to a config list to improve compatibility
> improve lick your wounds mod compatibility 

- LongWarOfTheChosen/Localization/LW_AlienPack_Integrated/XComGame.chn
- LongWarOfTheChosen/Localization/LW_AlienPack_Integrated/XComGame.cht
- LongWarOfTheChosen/Localization/LW_Overhaul.chn
- LongWarOfTheChosen/Localization/LW_Overhaul.cht
Update the Chinese translation of the patch notes
> Update the Chinese translation of the patch notes

- LongWarOfTheChosen/Localization/XComGame.chn
- LongWarOfTheChosen/Localization/XComGame.cht
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIOutpostManagement.uc
1.Optimize some Chinese translations
2.Disable the Adviser Loadout button when the Adviser is a scientist or an engineer
> Optimize Chinese translation and refine the enable/disable logic for the Adviser Loadout button.

- LongWarOfTheChosen/Localization/XComGame.chn
- LongWarOfTheChosen/Localization/XComGame.cht
- LongWarOfTheChosen/Localization/XComGame.esn
- LongWarOfTheChosen/Localization/XComGame.int
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/LWTacticalMissionUnitSpawner.uc
- LongWarOfTheChosen/Src/LW_Overhaul/Classes/UIOutpostManagement.uc
- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2DownloadableContentInfo_LWPerkPack.uc
> Localization updates

- LongWarOfTheChosen/Localization/LW_PerkPack_Integrated/XComGame.int
specify that the ability grants one additional repair charge
> update enhanced repair systems description

- LongWarOfTheChosen/Config/XComClassData.ini
it was set to primary weapon which caused it to break animations
> correct homing mine config

- LongWarOfTheChosen/Localization/XComGame.int
Clarified the role of the laser/cg autocannons in their descriptions and removed mention of 2 charges for prototype plasma blaster.
> Laser/CG Autocannon & Prototype Plasma Blaster Description Update

- LongWarOfTheChosen/Config/XComLW_FactionBalance.ini
- LongWarOfTheChosen/Config/XComLW_Toolbox.ini
- LongWarOfTheChosen/Localization/LW_FactionBalance/XComGame.int
No more Skrimishers fighting the Alliens
> Various config typos

- LongWarOfTheChosen/Localization/XComGame.int
POI rewards now say "Point of Interest" and Facility Lead rewards now say "Facility Lead".
> Clarify Remaining "Intel Package" Rewards

- LongWarOfTheChosen/Src/LW_AlienPack_Integrated/Classes/X2Ability_LWAlienAbilities.uc
Extremely minor nitpick, but the red flyover bothered me, okay?
> Ready For Anything's Flyover will be green if used by XCom

- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Ability_LW_RangerAbilitySet.uc
- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Ability_PerkPackAbilitySet2.uc
- LongWarOfTheChosen/Src/LW_WeaponsAndArmor/Classes/X2DownloadableContentInfo_LW_WeaponsAndArmor.uc
> Hacking bonuses from Spark Bit and Advanced Logic are now correctly shown in the UI

- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_CloseandPersonal.uc
- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_KillerInstinct.uc
- LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_LoneWolf.uc
Remove more checks that require abilities to be attached to weapon to benefit from the bonus.
> Remove the source weapon check from more perks

- LongWarOfTheChosen/Src/LW_Toolbox_Integrated/Classes/XComGameState_Unit_LWRandomizedStats.uc
Not the most-polished possible, it currently needs to pass both the Template-specific Min/Max AND the default Min/Max.
Useful when your Min/Max is lower than the default, but otherwise breaks. Maybe address it?
> Config hook for NCE Template-based StatCaps 

- LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2Effect_IRI_SoulStorm.uc
> Fix SoulStorm's environmental destruction effect also affecting the caster
